# -*- coding: utf-8 -*-
"""Junior Data analyst project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dHpCftpGZJM2LI4L64-V8TAFr1Gj_AE
"""

# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# Load the CSV file into a DataFrame
file_path = "/content/Junior Data Analyst _ Data (1).csv"
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(df.head())

# Check for any missing values in the DataFrame
print(df.isnull().sum())

# Splitting the dataset into features (X) and target variable (y)
X = df[['hour', 'date/hour start', 'solar electricity generation(kWh)']]
y = df['Electric usage (kWh)']